name: Build CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
<<<<<<< HEAD
<<<<<<< HEAD
=======
>>>>>>> 097c9fd (Add CI (#33))
    defaults:
      run:
        working-directory: olympics-website

    steps:
      - uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 9
=======

    steps:
      - uses: actions/checkout@v4
>>>>>>> c726e6c (Add CI (#32))
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
<<<<<<< HEAD
          cache: 'pnpm'
          cache-dependency-path: olympics-website/pnpm-lock.yaml
      - run: pnpm install --frozen-lockfile
      - run: pnpm run build
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
=======
          cache: 'npm'
          cache-dependency-path: olympics-website/package-lock.json
      - run: npm ci
      - run: npm run build
>>>>>>> c726e6c (Add CI (#32))
